name: Deploy Astro site to GitHub Pages

on:
  push:
    branches:
      - main  # ou master selon votre branche par défaut

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # ou la version que vous utilisez

      - name: Install dependencies
        run: npm install

      - name: Build Astro site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          # Si votre site est dans un sous-répertoire, spécifiez le base url dans astro.config.mjs (déjà fait)
